# Generated by Django 4.1.7 on 2024-06-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_bajaalumnos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
