# Generated by Django 5.0.6 on 2024-06-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_bajaalumnos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalizacion',
            name='estadoCanalizados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
