# Generated by Django 5.0.6 on 2024-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_canalizacion_estadocanalizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalizacion',
            name='motivo',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canalizacion',
            name='observaciones',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
