# Generated by Django 5.0.6 on 2024-07-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_usuarios_apellido_remove_usuarios_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='token',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
