# Generated by Django 4.1.7 on 2024-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_periodo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontutorial',
            name='evidencias',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='acciontutorial',
            name='cierreTutorias',
            field=models.TextField(blank=True),
        ),
    ]
