# Generated by Django 4.1.7 on 2024-06-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_acciontutorial_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciontutorial',
            name='cierreTutorias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
