# Generated by Django 5.0.6 on 2024-07-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=255)),
                ('tutor', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=50)),
                ('fechaR', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('noControl', models.CharField(max_length=8, unique=True)),
                ('telCasa', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telCelular', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
