# Generated by Django 5.0.6 on 2024-07-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_estudiantes_delete_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='Estudiante',
        ),
    ]
