# Generated by Django 4.1.7 on 2024-06-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_acciontutorial_cierretutorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciontutorial',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuarios'),
        ),
    ]
