# Generated by Django 5.0.6 on 2024-07-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_conquienvives_estadocivil_huerfanode_numhermanos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfamiliares',
            name='conviveCon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='estadoCivil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfanoQuien',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='totalHermanos',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='datosfamiliares',
            name='idEstudiante',
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfano',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ConQuienVives',
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
        migrations.DeleteModel(
            name='HuerfanoDe',
        ),
        migrations.DeleteModel(
            name='NumHermanos',
        ),
    ]
