# Generated by Django 5.0.6 on 2024-07-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_acciontutorial_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionindividual',
            name='bajasAlumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.bajaalumnos'),
        ),
    ]
