# Generated by Django 5.0.6 on 2024-07-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_datosfamiliares_convivecon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfamiliares',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estudiante'),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='conviveCon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='estadoCivil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfano',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfanoQuien',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='otra_situacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
