# Generated by Django 5.0.6 on 2024-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_atencionindividual_bajasalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionindividual',
            name='estado',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
