# Generated by Django 5.0.6 on 2024-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_datosfamiliares_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosfamiliares',
            old_name='estudiante',
            new_name='idEstudiante',
        ),
        migrations.RemoveField(
            model_name='datosfamiliares',
            name='idDatosf',
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
