# Generated by Django 5.0.7 on 2024-07-12 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_rename_estudiante_datosfamiliares_idestudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aficiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoLibre', models.IntegerField()),
                ('horasLibre', models.IntegerField()),
                ('idEstudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='DatosSocioeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivienda', models.IntegerField()),
                ('tenencia', models.IntegerField()),
                ('cuentaCon', models.TextField()),
                ('habitaciones', models.IntegerField()),
                ('vehiculos', models.IntegerField()),
                ('manutencion', models.IntegerField()),
                ('trabajoPapa', models.IntegerField()),
                ('trabajoextraPapa', models.TextField()),
                ('trabajoMama', models.IntegerField()),
                ('trabajoextraMama', models.TextField()),
                ('ingresoFam', models.IntegerField()),
                ('contribuyentes', models.IntegerField()),
                ('dependientesIngresos', models.IntegerField()),
                ('trabajas', models.BooleanField(default=False)),
                ('relacionCarrera', models.IntegerField()),
                ('idEstudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Personalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborasCasa', models.BooleanField(default=False)),
                ('colaboracion', models.IntegerField()),
                ('ambienteFamiliar', models.IntegerField()),
                ('hablaFamiliar', models.IntegerField()),
                ('comunicacion', models.BooleanField(default=False)),
                ('idEstudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estudiante')),
            ],
        ),
    ]
