# Generated by Django 5.0.6 on 2024-07-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_atencionindividual_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionindividual',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
