# Generated by Django 5.0.7 on 2024-07-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_aficiones_datossocioeconomicos_personalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datossocioeconomicos',
            name='idEstudiante',
        ),
        migrations.RemoveField(
            model_name='personalidad',
            name='idEstudiante',
        ),
        migrations.DeleteModel(
            name='Aficiones',
        ),
        migrations.DeleteModel(
            name='DatosSocioeconomicos',
        ),
        migrations.DeleteModel(
            name='Personalidad',
        ),
    ]
