# Generated by Django 5.0.6 on 2024-07-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_atencionindividual_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciontutor',
            name='respuestaUno',
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='cordialidad',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='disposicionTutor',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='dominio',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='impacto',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='orientacion',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='planTrabajo',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='proposito',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='puntualidad',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='serviciosApoyo',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='temasInteres',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
        migrations.AddField(
            model_name='evaluaciontutor',
            name='temasPrevistos',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Casi nunca'), (3, 'Casi siempre'), (4, 'Siempre')], default=4),
        ),
    ]
