# Generated by Django 5.0.7 on 2024-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_estudiante_nocontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
