# Generated by Django 4.1.7 on 2024-07-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_evaluaciontutor_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionindividual',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='cordialidad',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='disposicionTutor',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='dominio',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='impacto',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='orientacion',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='planTrabajo',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='proposito',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='puntualidad',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='serviciosApoyo',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='temasInteres',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
        migrations.AlterField(
            model_name='evaluaciontutor',
            name='temasPrevistos',
            field=models.IntegerField(choices=[[1, 'Nunca'], [2, 'Casi nunca'], [3, 'Casi siempre'], [4, 'Siempre']], default=4),
        ),
    ]
