# Generated by Django 4.1.7 on 2024-07-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_atencionindividual_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciontutor',
            name='cicloEvaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.periodo'),
            preserve_default=False,
        ),
    ]
