# Generated by Django 5.0.7 on 2024-07-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_estudiante_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socioeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivienda', models.IntegerField()),
                ('tenencia', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('vehiculos', models.IntegerField()),
                ('trabajoPapa', models.IntegerField()),
                ('trabajoextraPapa', models.CharField(blank=True, max_length=100)),
                ('trabajoMama', models.IntegerField()),
                ('trabajoextraMama', models.CharField(blank=True, max_length=100)),
                ('manutencion', models.IntegerField()),
                ('trabajas', models.BooleanField()),
                ('relacionCarrera', models.IntegerField()),
                ('ingresoFam', models.IntegerField()),
                ('contribuyentes', models.IntegerField()),
                ('dependientesIngresos', models.IntegerField()),
                ('idEstudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estudiante')),
            ],
        ),
    ]
