# Generated by Django 5.0.7 on 2024-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_socioeconomicos_manutencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicos',
            name='ingresoFam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajas',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
    ]
