# Generated by Django 5.0.7 on 2024-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_socioeconomicos_ingresofam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicos',
            name='ingresoFam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='manutencion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='relacionCarrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='tenencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoMama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoPapa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoextraMama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoextraPapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vivienda',
            field=models.CharField(max_length=100),
        ),
    ]
