# Generated by Django 5.0.7 on 2024-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_socioeconomicos_ingresofam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
