# Generated by Django 5.0.7 on 2024-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_alter_socioeconomicos_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vivienda',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
