# Generated by Django 5.0.7 on 2024-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_socioeconomicos_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
