# Generated by Django 5.0.7 on 2024-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_antecedenteacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='promedio',
            field=models.FloatField(),
        ),
    ]
