# Generated by Django 5.0.7 on 2024-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_alter_antecedenteacademico_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='modalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='promedio',
            field=models.CharField(max_length=50),
        ),
    ]
