# Generated by Django 5.0.7 on 2024-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_habitosestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='duracion',
            field=models.CharField(choices=[('Menos de uno', 'Menos de uno'), ('Alrededor de un año', 'Alrededor de un año'), ('Más de un año', 'Más de un año'), ('Dos años', 'Dos años'), ('Tres años', 'Tres años'), ('Más de tres años', 'Más de tres años')], max_length=50),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='modalidad',
            field=models.CharField(choices=[('Escolarizada', 'Escolarizada'), ('Semiescolarizada', 'Semiescolarizada'), ('Abierta', 'Abierta'), ('A distancia', 'A distancia'), ('Examen único', 'Examen único')], max_length=50),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='nivelRep',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Carrera Técnica', 'Carrera Técnica'), ('Otra', 'Otra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='obstaculos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='promedio',
            field=models.CharField(choices=[('Entre 10 y 9.5', 'Entre 10 y 9.5'), ('Entre 9.4 y 9.0', 'Entre 9.4 y 9.0'), ('Entre 8.9 y 8.5', 'Entre 8.9 y 8.5'), ('Entre 8.4 y 8.0', 'Entre 8.4 y 8.0'), ('Entre 7.9 y 7.5', 'Entre 7.9 y 7.5'), ('Entre 7.4 y 6.0', 'Entre 7.4 y 6.0'), ('Menos de 6', 'Menos de 6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='rendimiento',
            field=models.CharField(choices=[('Muy bueno', 'Muy bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='repAnio',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='gustoLectura',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='horario',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='musica',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='sitioLectura',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='contribuyentes',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Más de 5', 'Más de 5')], default='', max_length=100, verbose_name='contribuyentes'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='dependientesIngresos',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Más de 5', 'Más de 5')], default='', max_length=100, verbose_name='dependientesIngresos'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='habitaciones',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('Más de 10', 'Más de 10')], default='', max_length=100, verbose_name='habitaciones'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='ingresoFam',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('De 3,000 a 5,000', 'De 3,000 a 5,000'), ('De 5,001 a 10,000', 'De 5,001 a 10,000'), ('De 10,001 a 15,000', 'De 10,001 a 15,000'), ('De 15,001 a 20,000', 'De 15,001 a 20,000'), ('De 20,001 a 25,000', 'De 20,001 a 25,000'), ('De 25,001 a 26,000', 'De 25,001 a 26,000'), ('De 26,001 a 30,000', 'De 26,001 a 30,000'), ('Más de 30,000', 'Más de 30,000')], default='', max_length=100, verbose_name='ingresoFam'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='manutencion',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Por cuenta propia', 'Por cuenta propia'), ('Mis papás costean mis gastos', 'Mis papás costean mis gastos'), ('Parte mis papás, parte yo', 'Parte mis papás, parte yo')], default='', max_length=100, verbose_name='manutencion'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='relacionCarrera',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Mucho', 'Mucho'), ('Algo', 'Algo'), ('Nada', 'Nada')], default='', max_length=100, verbose_name='relacionCarrera'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='tenencia',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Propia', 'Propia'), ('Rentada', 'Rentada'), ('Prestada', 'Prestada'), ('Hipotecada', 'Hipotecada'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='tenencia'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajas',
            field=models.BooleanField(default=False, verbose_name='trabajas'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoMama',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Desempleado(a)', 'Desempleado(a)'), ('Jubilado(a) o pensionado(a)', 'Jubilado(a) o pensionado(a)'), ('Empleado del gobierno(a)', 'Empleado del gobierno(a)'), ('Agroproductor(a)', 'Agroproductor(a)'), ('Operario de producción(a)', 'Operario de producción(a)'), ('Comerciante', 'Comerciante'), ('Profesionista trabaja por cuenta propia', 'Profesionista trabaja por cuenta propia'), ('Militar (ejército o armada)', 'Militar (ejército o armada)'), ('Otro', 'Otro')], default='', max_length=100, verbose_name='trabajoMama'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoPapa',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Desempleado(a)', 'Desempleado(a)'), ('Jubilado(a) o pensionado(a)', 'Jubilado(a) o pensionado(a)'), ('Empleado del gobierno(a)', 'Empleado del gobierno(a)'), ('Agroproductor(a)', 'Agroproductor(a)'), ('Operario de producción(a)', 'Operario de producción(a)'), ('Comerciante', 'Comerciante'), ('Profesionista trabaja por cuenta propia', 'Profesionista trabaja por cuenta propia'), ('Militar (ejército o armada)', 'Militar (ejército o armada)'), ('Otro', 'Otro')], default='', max_length=100, verbose_name='trabajoPapa'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoextraMama',
            field=models.CharField(blank=True, max_length=100, verbose_name='trabajoextraMama'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajoextraPapa',
            field=models.CharField(blank=True, max_length=100, verbose_name='trabajoextraPapa'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vehiculos',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('Más de 10', 'Más de 10')], default='', max_length=100, verbose_name='vehiculos'),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='vivienda',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Casa', 'Casa'), ('Casa en coto privado', 'Casa en coto privado'), ('Departamento', 'Departamento'), ('Departamento multifamiliar', 'Departamento multifamiliar'), ('Casa de huéspedes', 'Casa de huéspedes')], default='', max_length=100, verbose_name='vivienda'),
        ),
    ]
