# Generated by Django 5.0.7 on 2024-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_alter_antecedenteacademico_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedenteacademico',
            name='repAnio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='conviveCon',
            field=models.CharField(choices=[('Mis papás', 'Mis papás'), ('Con mi papá', 'Con mi papá'), ('Con mi mamá', 'Con mi mamá'), ('Con mis parientes(tíos,abuelos,etc.)', 'Con mis parientes(tíos,abuelos,etc.)'), ('Con mis amigos', 'Con mis amigos'), ('Solo', 'Solo'), ('Otra situación', 'Otra situación')], max_length=200),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='estadoCivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Unión libre', 'Unión libre'), ('Divorciado(a)', 'Divorciado(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfano',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='huerfanoQuien',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Padre', 'Padre'), ('Madre', 'Madre'), ('Ambos', 'Ambos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='otra_situacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(choices=[('Licenciatura en Diseño y Gestión de Redes Logísticas', 'Licenciatura en Diseño y Gestión de Redes Logísticas'), ('Ingeniería en Energías Renovables', 'Ingeniería en Energías Renovables'), ('Licenciatura en Contaduría', 'Licenciatura en Contaduría'), ('Licenciatura en Gastronomía', 'Licenciatura en Gastronomía'), ('Ingeniería en Logística Comercial Global', 'Ingeniería en Logística Comercial Global'), ('Ingeniería en Mantenimiento Industrial', 'Ingeniería en Mantenimiento Industrial'), ('Ingeniería en Procesos Químicos', 'Ingeniería en Procesos Químicos'), ('Ingeniería en Desarrollo y Gestión de Software', 'Ingeniería en Desarrollo y Gestión de Software')], max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.CharField(choices=[('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('Más de 30', 'Más de 30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaR',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.CharField(choices=[('1-GAS-1', '1-GAS-1'), ('9-IDG-1', '9-IDG-1'), ('4-TID-1', '4-TID-1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='noControl',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tutor',
            field=models.CharField(choices=[('Guillermo Jair Rincón Cruzado', 'Guillermo Jair Rincón Cruzado'), ('Miriam Minerva Jiménez Lara', 'Miriam Minerva Jiménez Lara'), ('Heriberto Pérez Romero', 'Heriberto Pérez Romero'), ('Alicia Judith Figueroa García', 'Alicia Judith Figueroa García'), ('Juan Ríos Hernández', 'Juan Ríos Hernández'), ('Francisco Fortino Güereña Galaz', 'Francisco Fortino Güereña Galaz'), ('David Manuel Ramos Sánchez', 'David Manuel Ramos Sánchez'), ('Juan Manuel Fernández Álvarez', 'Juan Manuel Fernández Álvarez')], max_length=200),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='gustoLectura',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='horario',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='musica',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitosestudio',
            name='sitioLectura',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socioeconomicos',
            name='trabajas',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
    ]
