# Generated by Django 5.0.7 on 2024-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_alter_antecedenteacademico_repanio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='noControl',
            field=models.CharField(max_length=8),
        ),
    ]
