# Generated by Django 5.0.7 on 2024-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_datosaficiones_datospersonalidad_datossalud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datossalud',
            name='causaOperacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='causaOperacion'),
        ),
    ]
