# Generated by Django 5.0.7 on 2024-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_alter_datossalud_causaoperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonalidad',
            name='ambienteFamiliar',
            field=models.CharField(choices=[('Totalmente', 'Totalmente'), ('Bastante', 'Bastante'), ('Suficiente', 'Suficiente'), ('Regular', 'Regular'), ('Poco', 'Poco'), ('Nada', 'Nada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonalidad',
            name='colaboracion',
            field=models.CharField(choices=[('Mucho', 'Mucho'), ('Regular', 'Regular'), ('Solo lo necesario', 'Solo lo necesario'), ('Poco', 'Poco'), ('Nada', 'Nada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonalidad',
            name='colaborasCasa',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datospersonalidad',
            name='comunicacion',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datospersonalidad',
            name='hablaFamiliar',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Casi siempre', 'Casi siempre'), ('A veces', 'A veces'), ('Casi nunca', 'Casi nunca'), ('Nunca', 'Nunca')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datossalud',
            name='causaOperacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
